name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 1.19 ]
        os: [ debian ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
          --pull \
          --file Dockerfile \
          --tag chinayin/nginx:${{ matrix.major }} \
          --tag chinayin/nginx:$(grep -oE 'NGINX_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+') \
          .
      - name: Push image to Docker hub
        if: success()
        working-directory: ${{ matrix.major }}/${{ matrix.os }}/${{ matrix.variant }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push chinayin/nginx:${{ matrix.major }}
          docker push chinayin/nginx:$(grep -oE 'NGINX_VERSION [0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')
          docker logout
